import nodemailer from 'nodemailer';

const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: 'nids194914@gmail.com',
    pass: 'fdml idlv staf slwn',
  },
});

/**
 * Sends a pothole report email to the authorities with an attachment.
 * @param {Object} reportDetails - Details of the reported pothole.
 * @param {Object} attachment - { buffer, filename, contentType }
 */
export const sendReportEmail = async (reportDetails, attachment = null) => {
  console.log("Process initiated: Preparing email content and attachment...");
  
  const { latitude, longitude, severityLevel, imageUrl, description } = reportDetails;
  
  const mailOptions = {
    from: '"RoadVision AI System" <nids194914@gmail.com>',
    to: 'vikalpbordekar@gmail.com',
    subject: `🚨 CRITICAL ROAD DEFECT REPORT: ${severityLevel.toUpperCase()} SEVERITY`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; border: 1px solid #eee; padding: 20px;">
        <h2 style="color: #1a237e; border-bottom: 2px solid #1a237e; padding-bottom: 10px;">RoadVision AI Detection Report</h2>
        <p><strong>Status:</strong> Process initiated & Sent to Authority with Evidence Attachment</p>
        <hr>
        <p><strong>Severity:</strong> <span style="color: ${severityLevel === 'high' ? 'red' : 'orange'}; font-weight: bold;">${severityLevel.toUpperCase()}</span></p>
        <p><strong>Coordinates:</strong> ${latitude}, ${longitude}</p>
        <p><strong>Description:</strong> ${description || 'No additional description provided.'}</p>
        
        <div style="margin-top: 30px; padding: 15px; bg-color: #f9f9f9; border-radius: 5px;">
          <p style="font-size: 12px; color: #666;">This is an automated report generated by the RoadVision AI Monitoring System. The original high-resolution evidence is attached to this email.</p>
          <p style="font-size: 12px; color: #1a237e; font-weight: bold;">Reference ID: RV-${Date.now()}</p>
        </div>
      </div>
    `,
    attachments: attachment ? [{
      filename: attachment.filename,
      content: attachment.buffer,
      contentType: attachment.contentType
    }] : []
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log("Email sent: Log ID " + info.messageId);
    
    // Simulate "Mail read" for demonstration as requested
    setTimeout(() => {
      console.log("Mail read: Digital receipt confirmed by recipient server.");
    }, 2000);
    
    return info;
  } catch (error) {
    console.error("Email sending failed:", error);
    throw error;
  }
};
